# Generated by Django 5.0.4 on 2024-05-16 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('syllabus', models.TextField()),
                ('exam_pattern', models.TextField()),
                ('eligibility_criteria', models.TextField()),
                ('registration_procedure', models.TextField()),
                ('important_dates', models.TextField()),
                ('exam_centres', models.TextField()),
                ('educational_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.educationallevel')),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.examtype')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.state')),
            ],
        ),
        migrations.CreateModel(
            name='PreparationResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('resource_type', models.CharField(choices=[('Book', 'Book'), ('Online Course', 'Online Course'), ('Sample Paper', 'Sample Paper'), ('Preparation Tip', 'Preparation Tip')], max_length=100)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
            ],
        ),
        migrations.CreateModel(
            name='UserExamRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmarked_exams', models.ManyToManyField(related_name='bookmarked_by', to='exam.exam')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_exams', models.ManyToManyField(related_name='recommended_to', to='exam.exam')),
                ('registered_exams', models.ManyToManyField(related_name='registered_exams', to='exam.userexamregistration')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exam.userprofile')),
            ],
        ),
    ]
